### ISSUE TITLE
AUR package cannot be compiled, it throws errors

### ISSUE THREAD

**Issue by michaldybczak** [jplsek/puush-qt#1]
aur-puush-qt/src/puush-qt/src/checkShared.sh: linia 7: /etc/ld.so.conf.d/puush-qt.conf: No access
ldconfig: Can't create a temp bufor file /etc/ld.so.cache~: No access
make[1]: *** [Makefile:438: libpuush-qt.so.1.0.0] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-michaldybczak/aur-puush-qt/src/puush-qt/build/src'
make: *** [Makefile:89: sub-src-make_first-ordered] Error 2
==> ERROR: Error in build().
    Canceling...
==> ERROR:Makepkg wasn't able to build puush-qt.

**Comment by jplsek** [comment]
Thank you for the report!

I think I fixed it. Please try installing from the AUR again. You may need to delete the "/tmp/yaourt-tmp-michaldybczak/aur-puush-qt" directory in case yaourt says that it has already been built and won't update the build directory (I have this problem when using pacaur).

If that works, please report back.

**Comment by michaldybczak** [comment]
Yeah, now it works! Thanks 👍
